name: zapfull-security-scan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.3.0
      with:
        target: "http://dev.dashboard.probo.in/"

      
      
